### ISSUE TITLE
Vue 4 suppport?

### ISSUE THREAD

**Issue by peebles** [MeForma/vue-toaster#20]
$ vue --version
@vue/cli 4.5.12

In main.js

import Toaster from "@meforma/vue-toaster";
Vue.use(Toaster);

 WARNING  Compiled with 2 warnings                                                                                                                6:32:26 PM

 warning  in ./node_modules/@meforma/vue-toaster/src/helpers/mount-component.js

"export 'h' was not found in 'vue'

 warning  in ./node_modules/@meforma/vue-toaster/src/helpers/mount-component.js

"export 'render' was not found in 'vue'

Is this a version issue?  I just started using Vue ... I hope the eco system isn't like Python ... :)

**Comment by peebles** [comment]
Ok ... I am not using v4:

    "vue": "^2.6.11"

So maybe thats the problem.

**Comment by jprodrigues70** [comment]
Hi @peebles. This plugin is designed for Vue 3, if you are looking for a similar plugin for Vue 2, you can see https://www.npmjs.com/package/vue-toast-notification;

And vue 4 don't exists :D
